# Generated by Django 5.1.2 on 2024-10-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='token',
            table='tokens',
        ),
    ]
