# Generated by Django 5.1.2 on 2024-10-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0003_alter_token_tx_hash_alter_token_unique_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='tx_hash',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
